# https://github.com/cypress-io/github-action
name: Parallel Testing of jobs
on: push
jobs:
  opencart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command : npm run test:OpenCartReg

      - name: Cypress Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - OpenCart
          path: cypress/reports/html/
            #browser : firefox
  orangehrm-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command : npm run test:OrangeHRM

      - name: Cypress Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
           name: Mochawesome HTML Report- Orange - HRM
           path: cypress/reports/html/
            # browser : chrome          